effects:
  elements:
    sun:
      "on":
        heat: 1.5
    wind:
      travel_dissipation: 0.9 # Naturally occurring reduction of wind
      dissipation_cone: 90 # The angle at which wind might dissipate into neighbours
      dissipation_limiter: 2 # The higher, the more the dissipation concentrates in the cells directly in front of the wind
      "on": # How much of this resource is blown away by wind
        clouds: 0.5
        pollution: 1
    heat:
      "on":
        ice: 0.4 # Higher makes icebergs melt or solidify faster
        rain: 0.1 # Higher creates a higher threshold for rain to pour, according to temperature
        pollution: 0.01
        cloud_creation: 0.5
        wind: 0.1
    rain: # Reduction of elements by rain
      "on":
        heat: 1
        pollution: 1
        cloud_reduction: 3
    clouds:
      "on":
        sun: 1 # Sun blockage
    height:
      "on":
        wind: 0.1
        heat: 0.1
    pollution:
      "on":
        heat: 0.01
  biomes:
    ice:
      "on":
        heat: 4
    city:
      "on":
        pollution: 9
    forest:
      "on":
        pollution: 0.5
    sea:
      "on":
        heat: 1.2
        pollution: 0.6
thresholds:
  elements:
    rain:
      base: 5
  biomes:
    sea:
      freezing: -5
world:
  seed: 3 # Leave empty for random seed
  days: 365
  stabilisation_period: 150 # Amount of days we let the world stabilise before starting the year
  start:
    sea:
      temperature: 6
    ice:
      temperature: -6
    temperature: 6
    pollution: 5
    clouds: 2.5
  terrain:
    max_height: 16
    harshness: 4 # Higher -> more archipelago-like land. Lower -> fewer, bigger continents
    water_level: 9
    size: 20 # map size is size^2
  biomes:
    city:
      spread: 12  # Higher -> more of the biome will show around.
      threshold: 10  # Higher -> smaller, less connected biomes. max height = no biome at all.
    forest:
      spread: 6
      threshold: 8
    ice:
      spread: 4
      threshold: 14
