effects:
  elements:
    sun:
      "on":
        heat: 0.1
    wind:
      travel_dissipation: 0.9
      dissipation_cone: 135
      dissipation_limiter: 2
      "on":
        heat: 0.01
        clouds: 0.5
        pollution: 1
    heat:
      "on":
        ice: -1
        rain: 0.1
        pollution: 0.1
        cloud_creation: 0.1
        wind: 0.1
    rain:
      "on":
        heat: 0.5
        pollution: 1
        cloud_reduction: 1
    clouds:
      "on":
        sun: 1
    height:
      "on":
        wind: 0.1
        heat: 0.1
    pollution:
      "on":
        heat: 0.1
  biomes:
    ice:
      "on":
        heat: 1
    city:
      "on":
        pollution: 2
    forest:
      "on":
        pollution: 0.3
    sea:
      "on":
        heat: 1
        pollution: 0.5
thresholds:
  elements:
    rain:
      base: 5
  biomes:
    sea:
      freezing: -5
world:
  start:
    sea:
      temperature: 20
    ice:
      temperature: -30
    temperature: 16
    pollution: 0
    clouds: 1
  terrain:
    max_height: 16
    harshness: 4 # Higher -> more archipelago-like land. Lower -> fewer, bigger continents
    water_level: 9
    size: 35 # map size is size^2
  biomes:
    city:
      spread: 12  # Higher -> more of the biome will show around.
      threshold: 11  # Higher -> smaller, less connected biomes. max height = no biome at all.
    forest:
      spread: 6
      threshold: 8
    ice:
      spread: 4
      threshold: 14